#.github/HikLk/CICD_Sprint_12/workflows/CICD_Pipeline.yml

name: CI/CD Pipeline

on:
 push:
 branches: workBranch
 pull_request:
 branches: workBranch

jobs:
 build:
 name: Build and Test
 runs-on: windows-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v3

 - name: Set up Go
 uses: actions/setup-go@v3
 with:
 go-version: 1.22.2

 - name: Install dependencies
 run: go mod download

 - name: Build and test
 run: go test -v./...

 publish:
 name: Publish to Docker Hub
 needs: build
 runs-on: windows-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v3

 - name: Set up Docker Buildx
 uses: docker/setup-buildx-action@v2

 - name: Login to Docker Hub
 uses: docker/login-action@v2
 with:
 username: ${{ secrets.DOCKER_USERNAME }}
 password: ${{ secrets.DOCKER_PASSWORD }}

 - name: Set up Docker Access Token
 uses: docker/login-action@v2
 with:
 username: ${{ secrets.DOCKER_USERNAME }}
 password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

 - name: Build and push
 uses: docker/build-push-action@v3
 with:
 context:.
 push: true
 tags: hiklk/CICD_Pipleline:v1

 #- name: Image digest
 #run: echo ${{ steps.push.outputs.digest }}